-- MySQL Script generated by MySQL Workbench
-- Tue Sep 16 20:58:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdautenticacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdautenticacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdautenticacao` DEFAULT CHARACTER SET utf8 ;
USE `bdautenticacao` ;

-- -----------------------------------------------------
-- Table `bdautenticacao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdautenticacao`.`usuario` (
  `usuario_id` INT NOT NULL,
  `usuario_nome` VARCHAR(50) NOT NULL,
  `usuario_email` VARCHAR(50) NOT NULL,
  `usuario_senha` VARCHAR(255) NOT NULL,
  `usuario_data_nascimento` DATE NOT NULL,
  `usuario_status` INT NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdautenticacao`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdautenticacao`.`role` (
  `role_id` INT NOT NULL,
  `role_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdautenticacao`.`usuario_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdautenticacao`.`usuario_role` (
  `role_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  INDEX `fk_usuario_role_role_idx` (`role_id` ASC),
  INDEX `fk_usuario_role_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_role_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `bdautenticacao`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_role_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bdautenticacao`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
